<?php
declare(strict_types=1);

/** @version 1.0.2 */

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\DataLayer\Event\BeginCheckout as BeginCheckoutEvent;
use Yireo\GoogleTagManager2HyvaCheckout\MageWire\Checkout as CheckoutComponent;

/** @var Template $block */
/** @var BeginCheckoutEvent $beginCheckoutEvent */
/** @var CheckoutComponent $magewire */
$beginCheckoutEvent = $block->getData('begin_checkout_event');
?>
<div class="hidden">
    <script>
        window.addEventListener('ga:trigger-event', function (event) {
            yireoGoogleTagManager2Pusher(event.detail, 'Hyva Checkout');
        });

        (function () {
            yireoGoogleTagManager2Pusher(<?= /* @noEscape */ json_encode($beginCheckoutEvent->get()) ?>, 'Hyva Checkout');
        })();
    </script>
</div>
